name: Updatertest

on: workflow_dispatch


env:
  FING_API_KEY: ${{ secrets.FING_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6
      - name: Install poetry
        run: pip install poetry==1.2.2
      - name: cache venv
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - run: poetry install
      - name: Update price forecasts
        run: poetry run python src/app/update_forecast.py
