name: Updatertest

on:
  schedule:
    - cron:  '20 * * * *' #run every 20min

env:
  FING_API_KEY: ${{ secrets.FING_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6
      - name: Install dependencies
        run: poetry install
      - name: Update price forecasts
        run: python3 src/app/update_forecast.py
