name: Updatertest

on: workflow_dispatch

env:
  FING_API_KEY: ${{ secrets.FING_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Update forecasts
        run: python src/app/update_forecast.py
      - name: Commit changes
        run: |
          git config --local user.name "forecaster"
          git add forecast_data/forecasts.csv
          git commit -m "Forecast update"
      - name: Push updated forecast
        uses: ad-m/github-push-action@py-scripts
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          force: true
